apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulsecheck
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml
commonLabels:
  app.kubernetes.io/part-of: pulsecheck
